FROM oraclelinux:7-slim as builder

RUN  yum -y install oracle-release-el7 oracle-nodejs-release-el7 && \
  yum-config-manager --disable ol7_developer_EPEL && \
  yum -y install oracle-instantclient19.3-basiclite nodejs && \
  rm -rf /var/cache/yum

# Get a new image
FROM node:18-alpine3.15

# Copy the Instant Client libraries, licenses and config file from the previous image
COPY --from=builder /usr/lib/oracle /usr/lib/oracle
COPY --from=builder /usr/share/oracle /usr/share/oracle
COPY --from=builder /etc/ld.so.conf.d/oracle-instantclient.conf /etc/ld.so.conf.d/oracle-instantclient.conf

WORKDIR /home/node/app
RUN chown node:node -R /home/node/app
USER node
# Install app dependencies
COPY --chown=node package*.json ./
RUN npm install --production
COPY --chown=node . .


# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0 PORT=8000

EXPOSE ${PORT}
CMD [ "node", "server/server.js" ]

# docker build --no-cache -t migutak/ecollect_apis:6.2.4 .
# npm install --cache /tmp/empty-cache
# npm cache clean