apiVersion: v1
kind: Service
metadata:
  name: ecollectapis-service
  namespace:
spec:
  selector:
    app: ecollectapis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30010
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecollectapis
  labels:
    app: ecollectapis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecollectapis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ecollectapis
    spec:
      containers:
      - name: ecollectapis
        image: migutak/ecollectapis:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ecolconfigmap
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ecolconfigmap
              key: port
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: ecolconfigmap
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ecolsecret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecolsecret
              key: dbpassword
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "500m"

